[project]
name = "clofftext"
version = "0.1.0"
description = "CLI tool for when you need concise information quicker -.-"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain>=0.3.14",
    "langchain-google-genai>=2.0.8",
    "python-dotenv>=1.0.1",
]
